### ISSUE TITLE
Reduce length of generate relationships

### ISSUE THREAD

**Issue by jptissot** [sebastienros/yessql#217]
In MySql, the Migration fails because the generated Identifier name is too long.
In Postgres, the identifiers are truncated to the max length of 64 characters and sometimes causes duplicate identifiers exception.

Related to : 
https://github.com/OrchardCMS/OrchardCore/pull/4802
https://github.com/OrchardCMS/OrchardCore/issues/4655

**Comment by deanmarcussen** [comment]
Comments from another issue. I assume this issue is related to the name length of the Index Table Name

From @sebastienros 
Could we instead detect that the index will be too long, and internally (yessql) use a constant hash (one that doesn't change from machine to machine) as the actual name? Or at least keep the first N letters and complete with a hash?

The YesSql dialects would have the max length for these index names, and we could compute the length of the prefix based on that and the length of the hash (of the full string).
