### ISSUE TITLE
Query on column == (variable with null value) doesn't yield results while it should - the sequel

### ISSUE THREAD

**Issue by sfmskywalker** [sebastienros/yessql#298]
When I perform the following query:

```csharp
var authorName = default(string);
var ps = session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == authorName).ListAsync().Result;
```

0 results are returned, even if there are actually blog posts where Author = NULL.

HOWEVER, as was fixed as part of #89, the following works fine:

```csharp
var ps = session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == null).ListAsync().Result;
```

Notice that it works when I use a literal `null` value when performing the query (one result is returned), but not when I supply a variable with a null value.

Repro steps:

```csharp
// creating a blog post with a null author

var author = default(string);

var post = new BlogPost
{
    Title = "Hello YesSql",
    Author = author,
    Content = "Hello",
    PublishedUtc = DateTime.UtcNow,
};

// saving the post to the database
using (var session = store.CreateSession())
{
    session.Save(post);
}

// loading blog posts by author
using (var session = store.CreateSession())
{
    // This yields 1 result:
    //var ps = await session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == null).ListAsync();

    // But this doesn't:
    var ps = await session.Query<BlogPost, BlogPostByAuthor>().Where(x => x.Author == author).ListAsync();

    Debug.Assert(ps.Any()); // Fails -> there are 0 results
}
```

**Comment by sebastienros** [comment]
This one is interesting. I assume that in the end it creates something like `author = @p1` and sends `null` as a parameter, but the query might just not work since it should be `author IS NULL`. I will add a unit test first to see if this doesn't work on any database.

I could check if a variable is null before creating a parameter. However that would worry me since compiled queries cache the query, and the query would then differ if an argument is null.
