### ISSUE TITLE
Concurrency checking on null Version

### ISSUE THREAD

**Issue by jtkech** [sebastienros/yessql#343]
Related to https://github.com/OrchardCMS/OrchardCore/issues/8470

After upgrading an application, if there is an existing document whose `Version` column is NULL, if we save this document using the checkConcurrency option, it fails because the generated command includes `where ... and [Version] = 0`.

As i understand an existing Version "can't" be equal to 0, but >= 1 or NULL, so when we update a document whose previous version has been mapped to 0, we could use `[Version] is null` or maybe `([Version] = 0 or [Version] is null)`.

**Comment by Skrypt** [comment]
I will add that migrations might fail if this is not taken care of.

**Comment by deanmarcussen** [comment]
I had a look at this, because I had some memory of fixing something related. Need to check more.

But @Skrypt can you look at the constraints on your `Document` table and see if you have a default(0) for the `Version` column. 

The create script should look include this...

`ALTER TABLE [dbo].[Document] ADD  DEFAULT ((0)) FOR [Version]`

If I remember rightly there was a short window where people were creating their own `Version` column because the migration failed, and I suspect anyone who created it manually didn't get the necessary constraint.

So it maybe that this impacts only on databases with the missing constraint.

**Comment by Skrypt** [comment]
![image](https://user-images.githubusercontent.com/3228637/109189475-0b004700-7762-11eb-822c-6c52a30ec0cd.png)

**Comment by Skrypt** [comment]
I think that the issue is not the default value. It's the fact that this column allows a null value.

**Comment by deanmarcussen** [comment]
> That's probably why it didn't get migrated not allowing a null value.

yes, that's exactly why.

It maybe too late now, but it would still help to know if you had the constraint. Which I suspect you didn't, which is what's letting it be null.

The constraint should have forced it up to 0.

**Comment by Skrypt** [comment]
I had no Version column it got added with the default(0) value after the table was created. So basically, when the column got added it was allowing a null value ; so for the records that we're there it set them as null. Because a default value always gets affected on the CREATE of a row record if you specify none. But it's not affecting a default value on an UPDATE.
