### ISSUE TITLE
Violation of PRIMARY KEY constraint 'PK__t4h_Docu__3214EC07B34ED974'. Cannot insert duplicate key in object 'dbo.t4h_Document'. The duplicate key value is (81)

### ISSUE THREAD

**Issue by bashuss** [sebastienros/yessql#379]
This Issue was first reported on Orchard Core:
https://github.com/OrchardCMS/OrchardCore/issues/9088

### In short:
Trying to create new Users in Orchard Core did not work and created the error and Stack-Trace reported to the ticket above.
### Context:
1. Two Instances of Orchard Core were running at the same time on the same database, one of them in Visual Studio, one as a live preview.
2. `Identifiers` table seemed to have a value above `max id` of documents, but the ids causing this error were in the range below `max id`
3. After stopping both instances and just starting one, the system recovered after one insuccessful try.
4. Even after this one instance recovered, the inserted new ids were below `max id` and the `nextval` value in `identifiers` pointed to the same value as when the system did not work.
5. Obviously, as lower ids could be inserted, there are unused ids below `max id` in my `documents` table
### Hypothesis
1. There is a mechanism (intended or not), that recovers unused ids below `max id`, but the ids that one instances claims in the range below `max id` are not represented in the database and therefore not communicated to other instances.

### Version
In my Orchard Core Version 1.0.0.0 RC2 stable, the used YesSql still seems to be way below the current version.

**Comment by jtkech** [comment]
As a reminder

In case the `nextval` of the `Identifiers` table was not updated correctly, we could take into account, at least on startup, the current `max Id` of the related document table, this to prevent to lease a new block overlapping existing Ids.

**Comment by Skrypt** [comment]
I don't agree. See the table name Primary Key constraint triggered here for the Docu ... ment table. So if you have 2 different Identifiers table and one that starts from an Id that is already taken in the Document table then it will trigger this Violation.

**Comment by Skrypt** [comment]
## Repro steps

Create a new tenant using SQL Server with the "sa" user which should be in the "dbo" schema by default.

https://user-images.githubusercontent.com/3228637/147000330-1aba388b-16a8-4a01-a9b5-5765b30e9fdd.mp4

Here we can find the "sa" user on the database by looking at the "dbo" user. It's the defaults permissions set by SQL Server ...

Here is the setup screen of Orchard using the sa user in the connection string : 

![image](https://user-images.githubusercontent.com/3228637/147000502-aabda493-cf76-4837-9135-fdd03487be67.png)

Once the setup is done you should get the database tables generated like these : 

![image](https://user-images.githubusercontent.com/3228637/147000669-f4cbb901-f5ea-4bdf-b9de-ef795bf61a1a.png)

We can see that there is only one "Identifiers" table created from setup which is totally fine.

Now let's create a new user to assign to our database and that would also be an owner of this database.
We will create this users and assign him a different schema than "dbo" and for the exercice we will use "db_owner" as it should work too.

![image](https://user-images.githubusercontent.com/3228637/147000924-b3c8cee4-430b-4ec7-9e4d-0939b9b0b9ea.png)

Now let's modify our database connection string in the appsettings.json file of our newly created tenant.

![image](https://user-images.githubusercontent.com/3228637/147001034-57914df7-6f19-4a02-8373-65b717da4482.png)

Now let's restart debugging in SQL Server to see if this works.

![image](https://user-images.githubusercontent.com/3228637/147001209-094e7a40-1ffe-4c4c-b41c-dae9374143c7.png)

I'm getting this exception now because I forgot to assign the user membership on the database.

![image](https://user-images.githubusercontent.com/3228637/147001375-90531cdc-3883-4eb6-9907-5a6be18f31a3.png)

Now it's working because I affected the proper membership on the user : 

![image](https://user-images.githubusercontent.com/3228637/147001416-c2702798-8960-4b31-8bc3-f04949719e75.png)

But let's see if what it did to the database : 

![image](https://user-images.githubusercontent.com/3228637/147001504-e3f57f5b-2e48-4624-b353-5035d4cd8bb1.png)

Now I have 2 different "Identifiers" table.

Et voilà! Repro steps 😄

**Comment by sebastienros** [comment]
Means that for SQLServer which should use a schema prefix for all queries. And would probably be in the configuration. Could be as part of the table prefix too, or on top of that since if would be `{schema}.{prefix}{table}` for Orchard. So maybe the dialect? Can it be specified in the connection string?

**Comment by Skrypt** [comment]
Quick answer is no for the connection string though will start reading this : 

https://www.sqlshack.com/a-walkthrough-of-sql-schema/

**Comment by Skrypt** [comment]
PostgreSQL must have the same issue.

https://www.postgresql.org/docs/9.1/ddl-schemas.html

**Comment by sebastienros** [comment]
Easy fix, have a schema property in the dialect, use "dbo" as default, let users change it to something else if they need. Update the dialect to use the schema and the prefix when formatting the table name.
