### ISSUE TITLE
Content column in document table gets truncated with long length data

### ISSUE THREAD

**Issue by psp589** [sebastienros/yessql#397]
When I try to store long length data and I check the document table i see the content gets truncated. 
Using sql server as documental bd i expected to store long length data like in a documental db.
the max seems to be 65538 characters
am I doing something wrong?
how could I accomplish this?
Thank you in advance.

**Comment by jersiovic** [comment]
Hey @psp589 hello!!
Happy to see you writting here, but sad to read the problem cause it means we are facing another problem in our project.

I'm going to reproduce the problem and debug yessql source to see where exactly is the problem, because at db is shouldn't be because nvarchar(MAX) supports much more characters

**Comment by psp589** [comment]
the problem is reading the column value with sqlserver but the value is not really truncated
