### ISSUE TITLE
InMemoryDbProvider is missing

### ISSUE THREAD

**Issue by hishamco** [sebastienros/yessql#56]
After that latest updates, seems the `InMemoryDbProvider` has been deleted, it was a good choice specially for testing purpose is there a reason for the deletion?

**Comment by sebastienros** [comment]
You can already do everything in memory using the Sqlite provider and using an in-memory connection string.
I will reintroduce technical providers (cache, hub, audit) later, by implementing custom IStore and ISession.

The idea will be that a CacheStore and CacheSession will proxy/wrap an actual store and session. Anything that can be fulfilled by these will return, otherwise the command will be passed to wrapped instance. 

#### Cache
Will prevent Get(int) from hitting the database if the instance is already known. Can also cache some queries and invalidate them on any write.

#### Hub
A composite for other sessions. For instance you can register two session on a hub, one for Sqlserver and on for Sqlite. Every write would go to both, reads would go to the main one. This allows replication of data. 

#### Audit
Like an event store. Records all actions in a storage format. You can then look at the history of changes on object, and also implement synchronization between systems, for instance by developing disconnected application that would synchronize the changes with the main system once reconnected.

**Comment by hishamco** [comment]
thanks for detailed information, but it would be nice if we have `InMemoryDbProvider` out-of-the-box instead of remembering the connection required for the SqLite to use the in memory data store

**Comment by sebastienros** [comment]
I see what you mean. Feel free to make a pr and add it as another extension method in the sqlite provider.

**Comment by sfmskywalker** [comment]
It appears the `InMemory` provider isn't available in the `dev` branch.

So I tried using the `Sqlite` provider's in-memory connection string (`"Filename=:memory:"`), which in itself works, except for the following issue: every time the connection goes out of scope, all of the created tables are lost from memory as well.

To work around this, I can create a custom DbConnectionFactory that always returns the same connection (effectively being a singleton). I tried this, and that seems to work nicely.

I can create a PR which adds support for in-memory Sqlite, unless we think we should re-introduce the `InMemoryDbProvider`?

**Comment by hishamco** [comment]
> It appears the InMemory provider isn't available in the dev branch.

Seems Seb remove it long time back ;)

**Comment by sfmskywalker** [comment]
Yeah, he moved that cheese way back ;)

In any case, here is a working YesSql provider using Sqlite's in-memory capability: https://github.com/elsa-workflows/elsa-core/tree/feature/elsa-2.0/src/core/YesSql.Provider.Sqlite.InMemory

Notice that it has to be a separate provider, since I had to subclass the `SqliteConnection` class, which means a different name is used in the dialect and interpreter dictionaries.

**Comment by hishamco** [comment]
I remembered I added this long time back in YesSql but I don't know the reason to remove it?!!
