### ISSUE TITLE
Ability to use not only RDBMS

### ISSUE THREAD

**Issue by xperiandri** [sebastienros/yessql#67]
Can you abstract high level commands (from Core library) into interfaces and use them by interface?
This way it is possible to use Azure Tables or any other store not only particular RDBMSs

**Comment by sebastienros** [comment]
No, it was a design decision to use SQL directly to provide better performance. I went the way you described at first, but SQL would still be necessary for indices. You can still provide a custom document store implementation like Azure Table, but SQL would still be required for custom queries. So there is no real advantage then.

**Comment by xperiandri** [comment]
But Azure Tables don't use SQL.
I just have to implement commands like `CreateDocument` the Azure Tables specific way.

Is my understanding correct that this high level commands are used by YesSQL?

**Comment by adamlepkowski** [comment]
@xperiandri I think It would be possible to persist your documents in Azure Tables but to query them you still need to use a SQL Server because this is how indexes work (https://github.com/sebastienros/yessql/wiki/Tutorial#creating-a-mapreduce-index). To be honest, I don't see any point to implement support for Azure Tables only for persisting document it can just introduce more issues (no transaction between Azure tables and SQL server).

**Comment by MedAnd** [comment]
Any plans to support Cosmos DB :relaxed:

**Comment by sebastienros** [comment]
YesSql needs and RDMS, by design.
