### ISSUE TITLE
Support complex indices

### ISSUE THREAD

**Issue by gentledepp** [sebastienros/yessql#71]
Hi!

I recently watched the YesSql presenation from Orchard Harvest 2017 and went through the unittests.
What I could not find out is: 
Is it possible to create indices with the data of multiple different documents?

For now, I only saw that it was possible to create multiple indices for the same document. (User => User by Rolename, User by Username, ....)

However, I wonder if it was possible to create an index like this (example from RavenDB) wher I index a user by his/her region, country and orders:

```
public CustomerIndex()
{
    AddMap(customers => from customer in customers
        let region = LoadDocument(customer.RegionId)
        let country = LoadDocument(region.CountryId)
        let orders = LoadDocument(customer.OrderIds)
        select new
        {
            Id = customer.Id,
            CustomerName = customer.Name,
            RegionName = region.Name,
            CountryName = country.Name,
            OrdersProcessed = orders.Count(o => o.IsProcessed),
            ProductIds = orders.Select(o => o.ProductId)
        });
    StoreAllFields(FieldStorage.Yes);
}
```

This would be crucial to use Orchard 2 as an application framework, because there are many real world scenarios that require that kind of index.

But I doubt that this is possible because - as far as I know - YesSql updates the indices within the same transaction. So those updates need to be **fast**

Am I right?

**Comment by gentledepp** [comment]
@sebastienros Any thoughts on this?
A simple "no, this is not planned to be a feature ever" would be fine too. I just need to know.

**Comment by sebastienros** [comment]
It's just that I haven't looked at it yet, needs more thinking before I can answer.

**Comment by flew2bits** [comment]
I don't see why this couldn't be accomplished in the IndexProvider. You'd have to pass a stripped down version of an ISession that only defines GetAsync. With that you could query any other object type by id which is what seems that gentledepp wants to do. Thoughts?

**Comment by flew2bits** [comment]
After digging into the code, it's a bit more complicated than I originally anticipated, but the hardest part would be avoiding introducing breaking changes. Here's my thoughts on what would need to change.

Create _IReadOnlySession_ which only defines _GetAsync<T>_, and remove _GetAsync<T>_ from _ISession_. _ISession_ would derive from _IReadOnlySession_. The _SessionExtensions_ class would be moved to the IReadOnlySession.cs since it will then extend _IReadOnlySession_.

_IIndexProvider.Describe_ would take an _IReadOnlySession_ as a second parameter, and this would have to be implemented in _IndexProvider.Describe_ which would just call the abstract method Describe. The abstract method would also need to take in an _IReadOnlySession_ **This is a breaking change as any implementation of _IndexProvider<T>_ would have to be changed to accept the session parameter**

_IStore.Describe_ would need to take an additional _IReadOnlySession_ parameter. Any method in _Session_ that calls _IStore.Describe_ would have to have _this_ added as a second parameter. _Store.Describe_ would then just pass the session to the _Describe_ method in each of the relevant index providers.

I think that's everything.

**Comment by flew2bits** [comment]
There is a timing issue, as well. All index updates would have to be deferred until after all documents are written to the database to make sure that anything within the transaction is available to the indexers. In the original example given, if the customer and all his orders were in the same transaction, those would all have to be committed to the database before the index could be created.

As it is stands, using _GetAsync_ within an indexer will result in a stack overflow since _GetAsync_ calls _CommitAsync_, which would in turn call _GetAsync_ in the indexer. So, there's a bit more work to make this happen.

**Comment by flew2bits** [comment]
I apologize for all the comments on this, but I just realized that passing the read-only session into the index provider doesn't make sense; it should be included with the _DescribeContext_ and only available to the _Map_ method (and maybe _Delete_; I'd have to think about that.) There would likely be no breaking changes in this case.

**Comment by sebastienros** [comment]
I assume it's obvious in the context of the RavenDb example because indices
are built in a later step so all documents are already stored.

Maybe this kind of feature should only be supported for deferred indices in
our case. But there is surely a way to commit the documents first, and
computed the indices later.

Also I am sure there are way to make this non-breaking.

**Comment by sebastienros** [comment]
In the example, how do you handle the fact that an Order is Processed. How is the Customer index updated automatically, how is it detected? Without having to explicitly call Save on the related  Customer document?

**Comment by flew2bits** [comment]
I hadn't considered that aspect of this issue, yet. I'll have to think about it some more.

**Comment by flew2bits** [comment]
What if you had a construct similar to how indexes are used? For example:

```csharp
    context.For<Customer>()
        .With<Region>(c => c.RegionId)
        .With<Country>(c => c.CountryId)
        .With<Order>(c => c.OrderIds)  // this would result in an IEnumerable of Orders
        .Map(...) // still have to figure out how to pass all of this in. Maybe with a tuple, or multiple overrides of Map
```

This way, the store can keep a map of what indexes would need to be updated whenever a document is saved. If the id of the related item (e.g. RegionId) is also saved in the index table, it should be possible to easily figure out what items need to be updated.

**Comment by sebastienros** [comment]
I don't think this is that easy. Let's say an Order is updated, how do you _find_ which Customer needs to be reloaded for updating its indices? Where is this relationship stored? It would require another table I assume.

Or by defining an associated query that would mark the Customer to be updated when an Order is processed, the opposite of your example `c => c.OrderIds`. This would be handled by an index that references the `Customer` from an `Order`.

```csharp
public class OrderIndexProvider : IndexProvider<Customer>
  context.For<CustomerByOrder, string>()
        .Map(customer =>
           customer.OrderIds.Select(id => new CustomerByOrder { OrderId = id }));

  // this returns a list of Customer instances that need their indices rebuilt, when an Order is modified
  context.For<Customer>()
    .InvalidatedBy<Order>(order, query => query.With<Customer, CustomerByOrder>(x => x.OrderId = order.OrderId));

```

**Comment by flew2bits** [comment]
I get what you're saying. I'm going to have to think about this some more.

**Comment by weedkiller** [comment]
Its easier with [LiteDB fully C# & free with 2600 users,](https://github.com/mbdavid/LiteDB) since you can directly map the the second complex /index directly to the object.

**Comment by sebastienros** [comment]
I believe this is now handle. We can add indexes per session, with custom state. I used it in this index which needs to call other services to fetch some information. https://github.com/OrchardCMS/OrchardCore/blob/taxonomies/src/OrchardCore.Modules/OrchardCore.Taxonomies/Indexing/TaxonomyIndex.cs#L54

**Comment by jersiovic** [comment]
> ay an Order is updated, how do you _find_ which Customer needs to be reloaded for updating its indices? Where is this relationship stored

How did you solved this?

**Comment by jersiovic** [comment]
> I don't think this is that easy. Let's say an Order is updated, how do you _find_ which Customer needs to be reloaded for updating its indices? Where is this relationship stored? It would require another table I assume.
> 
> Or by defining an associated query that would mark the Customer to be updated when an Order is processed, the opposite of your example `c => c.OrderIds`. This would be handled by an index that references the `Customer` from an `Order`.
> 
> ```cs
> public class OrderIndexProvider : IndexProvider<Customer>
>   context.For<CustomerByOrder, string>()
>         .Map(customer =>
>            customer.OrderIds.Select(id => new CustomerByOrder { OrderId = id }));
> 
>   // this returns a list of Customer instances that need their indices rebuilt, when an Order is modified
>   context.For<Customer>()
>     .InvalidatedBy<Order>(order, query => query.With<Customer, CustomerByOrder>(x => x.OrderId = order.OrderId));
> ```

Finally do you solved this? I'm interested on the scenario where an index its invalidated by changes on other entities

**Comment by gentledepp** [comment]
@sebastienros I tried to lookup your example but got a 404

Could you add this sample as documentation or as an integration test so we can have a look?

I'd still be very very interested 😁
